//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSIT11404project1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booking
    {
        public int BookingID { get; set; }
        public int HouseKeyID { get; set; }
        public int BedInSpaceID { get; set; }
        public Nullable<System.DateTime> FromDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public Nullable<bool> IsConfirm { get; set; }
        public System.DateTime Createdate { get; set; }
        public Nullable<bool> IsRejected { get; set; }
        public Nullable<System.DateTime> ReplyDate { get; set; }
    
        public virtual BedDtails BedDtails { get; set; }
        public virtual HouseMain HouseMain { get; set; }
        public virtual HouseMain HouseMain1 { get; set; }
        public virtual Members Members { get; set; }
    }
}
