//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSIT11404project1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Doc
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Doc()
        {
            this.Msg = new HashSet<Msg>();
            this.Pic = new HashSet<Pic>();
        }
    
        public int DocID { get; set; }
        public int Nid { get; set; }
        public string Title { get; set; }
        public string Article { get; set; }
        public string CreateTime { get; set; }
        public string ModifyTime { get; set; }
        public bool IsShow { get; set; }
        public int Good { get; set; }
        public int PlaceID { get; set; }
        public int MoodID { get; set; }
    
        public virtual Mood Mood { get; set; }
        public virtual PlaceForBlog PlaceForBlog { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Msg> Msg { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pic> Pic { get; set; }
        public virtual Members Members { get; set; }
    }
}
