//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSIT11404project1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Flights
    {
        public int FlightID { get; set; }
        public int AirlineID { get; set; }
        public int TicketInfoID { get; set; }
        public string FromAirport { get; set; }
        public string FromAirportName { get; set; }
        public string FromAirportCity { get; set; }
        public string FromAirportCountry { get; set; }
        public string ToAirport { get; set; }
        public string ToAirportName { get; set; }
        public string ToAirportCity { get; set; }
        public string ToAirportCountry { get; set; }
        public System.DateTime DepartureDate { get; set; }
        public Nullable<System.DateTime> ReturnDate { get; set; }
        public int ScheduleID { get; set; }
        public Nullable<decimal> TicketPrice { get; set; }
    
        public virtual Airlines Airlines { get; set; }
        public virtual ScheduleDetails ScheduleDetails { get; set; }
        public virtual TicketInfo TicketInfo { get; set; }
    }
}
