//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSIT11404project1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HouseMain
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HouseMain()
        {
            this.BedDtails = new HashSet<BedDtails>();
            this.Booking = new HashSet<Booking>();
            this.Booking1 = new HashSet<Booking>();
            this.Calendar = new HashSet<Calendar>();
            this.HouseQuality = new HashSet<HouseQuality>();
            this.ImageForRoom = new HashSet<ImageForRoom>();
        }
    
        public int HouseKey { get; set; }
        public Nullable<int> HouseSourceID { get; set; }
        public Nullable<int> HouseSpaceTypeID { get; set; }
        public string Adress { get; set; }
        public string Country { get; set; }
        public string State { get; set; }
        public Nullable<int> BathroomNum { get; set; }
        public Nullable<int> BedroomNum { get; set; }
        public Nullable<bool> IsOwnerHome { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> MemberID { get; set; }
        public Nullable<int> PeopleAllowed { get; set; }
        public Nullable<int> BedAvailableNum { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> BadComment { get; set; }
        public string HouseName { get; set; }
        public Nullable<bool> IsFreeze { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BedDtails> BedDtails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Booking> Booking { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Booking> Booking1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Calendar> Calendar { get; set; }
        public virtual HouseSourceType HouseSourceType { get; set; }
        public virtual HouseSpace HouseSpace { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HouseQuality> HouseQuality { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ImageForRoom> ImageForRoom { get; set; }
        public virtual Members Members { get; set; }
    }
}
