//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSIT11404project1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Msg
    {
        public int MsgID { get; set; }
        public int DocID { get; set; }
        public string Msg1 { get; set; }
        public string CreateTime { get; set; }
        public Nullable<bool> IsShow { get; set; }
        public Nullable<int> Nid { get; set; }
    
        public virtual Doc Doc { get; set; }
        public virtual Members Members { get; set; }
    }
}
