//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSIT11404project1.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MSIT11404Entities : DbContext
    {
        public MSIT11404Entities()
            : base("name=MSIT11404Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BedDtails> BedDtails { get; set; }
        public virtual DbSet<BedSpaceCode> BedSpaceCode { get; set; }
        public virtual DbSet<BedType> BedType { get; set; }
        public virtual DbSet<Booking> Booking { get; set; }
        public virtual DbSet<Calendar> Calendar { get; set; }
        public virtual DbSet<HouseQuality> HouseQuality { get; set; }
        public virtual DbSet<HouseSourceType> HouseSourceType { get; set; }
        public virtual DbSet<HouseSpace> HouseSpace { get; set; }
        public virtual DbSet<ImageForRoom> ImageForRoom { get; set; }
        public virtual DbSet<Doc> Doc { get; set; }
        public virtual DbSet<Mood> Mood { get; set; }
        public virtual DbSet<Msg> Msg { get; set; }
        public virtual DbSet<Pic> Pic { get; set; }
        public virtual DbSet<PlaceForBlog> PlaceForBlog { get; set; }
        public virtual DbSet<JobList> JobList { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Airlines> Airlines { get; set; }
        public virtual DbSet<Flights> Flights { get; set; }
        public virtual DbSet<ScheduleDetails> ScheduleDetails { get; set; }
        public virtual DbSet<TicketInfo> TicketInfo { get; set; }
        public virtual DbSet<LoginRecord> LoginRecord { get; set; }
        public virtual DbSet<CartsProducts> CartsProducts { get; set; }
        public virtual DbSet<Categorys> Categorys { get; set; }
        public virtual DbSet<OrderDetails> OrderDetails { get; set; }
        public virtual DbSet<Orders> Orders { get; set; }
        public virtual DbSet<Products> Products { get; set; }
        public virtual DbSet<Cities> Cities { get; set; }
        public virtual DbSet<Hotels> Hotels { get; set; }
        public virtual DbSet<Message> Message { get; set; }
        public virtual DbSet<Places> Places { get; set; }
        public virtual DbSet<Restaurants> Restaurants { get; set; }
        public virtual DbSet<Travels> Travels { get; set; }
        public virtual DbSet<HouseMain> HouseMain { get; set; }
        public virtual DbSet<Members> Members { get; set; }
    }
}
